
CREATE TABLE IF NOT EXIST `#__siak_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) NOT NULL,
  `prodi` tinyint(4) unsigned DEFAULT NULL,
  `jurusan` tinyint(4) unsigned DEFAULT NULL,
  `kelas` tinyint(4) unsigned DEFAULT NULL,
  `tipe_user` tinyint(4) unsigned DEFAULT NULL,
  `angkatan` year(4) NULL DEFAULT NULL,
  `state` TINYINT NOT NULL DEFAULT 1,
  `no_ktp` varchar(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nidn` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nik` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dob` date NULL DEFAULT null,
  `pob` varchar(70) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kelamin` enum('LAKI LAKI','PEREMPUAN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_sipil` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agama` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_masuk` date NULL DEFAULT null,
  `tanggal_keluar` date NULL DEFAULT null,
  `alamat_1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alamat_2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kelurahan` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kecamatan` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kabupaten` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `propinsi` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kode_pos` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telepon` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `foto` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` datetime NULL DEFAULT NULL,
  `reset` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime DEFAULT NULL,
  `asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `usr_user` (`user_id`),
  CONSTRAINT `usr_user` FOREIGN KEY (`user_id`) REFERENCES `dev_users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=740 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;