
DROP TABLE IF EXISTS `#__siak_bobot_nilai`;
DROP TABLE IF EXISTS `#__siak_revisi_nilai`;
DROP TABLE IF EXISTS `#__siak_penangguhan_bayar`
DROP TABLE IF EXISTS `#__siak_sp_mk` 
DROP TABLE IF EXISTS `#__siak_sp`;
DROP TABLE IF EXISTS `#__siak_ta`;
DROP TABLE IF EXISTS `#__siak_kp`;
DROP TABLE IF EXISTS `#__siak_industri`;
DROP TABLE IF EXISTS `#__siak_sk`;
DROP TABLE IF EXISTS `#__siak_praktikum`;
DROP TABLE IF EXISTS `#__siak_jadwal_kbm`;
DROP TABLE IF EXISTS `#__siak_nilai`;
DROP TABLE IF EXISTS `#__siak_krs_items`;
DROP TABLE IF EXISTS `#__siak_krs`;
DROP TABLE IF EXISTS `#__siak_dosen_mk`;
DROP TABLE IF EXISTS `#__siak_pembayaran`;
DROP TABLE IF EXISTS `#__siak_mhs_status`;
DROP TABLE IF EXISTS `#__siak_dosen_wali`;
DROP TABLE IF EXISTS `#__siak_user`;
DROP TABLE IF EXISTS `#__siak_jenis_user`;
DROP TABLE IF EXISTS `#__siak_paket_mk`;
DROP TABLE IF EXISTS `#__siak_ruangan`;
DROP TABLE IF EXISTS `#__siak_semester`;
DROP TABLE IF EXISTS `#__siak_matakuliah`;
DROP TABLE IF EXISTS `#__siak_jenis_mk`;
DROP TABLE IF EXISTS `#__siak_kelas_mahasiswa`;
DROP TABLE IF EXISTS `#__siak_programs_pembelajaran`;
DROP TABLE IF EXISTS `#__siak_jurusan`;
DROP TABLE IF EXISTS `#__siak_prodi`;
DROP TABLE IF EXISTS `#__siak_jadwal_ujian`;

DROP TRIGGER IF EXISTS `#__siak_user_status_insert`;
DROP TRIGGER IF EXISTS `#__siak_user_status_update`;
DROP TRIGGER IF EXISTS `#__users_insert`;
DROP TRIGGER IF EXISTS `#__semester_totalSKS_insert`;
DROP TRIGGER IF EXISTS `#__semester_totalSKS_update`;
DROP TRIGGER IF EXISTS `#__semester_totalSKS_delete`;
DROP TRIGGER IF EXISTS `#__siak_krs_items_nilai_insert`;
DROP TRIGGER IF EXISTS `#__siak_krs_nilai_update`;